services:
  - type: web
    name: obasecash-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: DB_NAME
        value: obasecash.db
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: mysupersecretkey
